"""added status field in quotation model

Revision ID: 22303667d8c1
Revises: 4874a7a57793
Create Date: 2023-07-30 16:43:47.176210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22303667d8c1'
down_revision = '4874a7a57793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
