"""made changes to quotation and ride model to have many to one relationship

Revision ID: 588dac6d9227
Revises: 68a6e7986525
Create Date: 2023-07-31 12:14:33.989803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588dac6d9227'
down_revision = '68a6e7986525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ride_trip_id', type_='foreignkey')
        batch_op.drop_column('quotation_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quotation_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_ride_trip_id', 'quotations', ['quotation_id'], ['id'])

    # ### end Alembic commands ###
