""" added status to ride model

Revision ID: 68a6e7986525
Revises: 22303667d8c1
Create Date: 2023-07-30 20:03:18.587148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68a6e7986525'
down_revision = '22303667d8c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False,server_default='Pending'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
