"""empty message

Revision ID: 8f2fe149a560
Revises: adde6b258312
Create Date: 2023-07-31 19:28:58.406468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f2fe149a560'
down_revision = 'adde6b258312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('from_location', sa.String(length=100), nullable=False),
    sa.Column('to_location', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('quotation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ride')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ride',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('passenger_id', sa.INTEGER(), nullable=False),
    sa.Column('driver_id', sa.INTEGER(), nullable=True),
    sa.Column('from_location', sa.VARCHAR(length=100), nullable=False),
    sa.Column('to_location', sa.VARCHAR(length=100), nullable=False),
    sa.Column('trip_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'Pending'"), nullable=False),
    sa.Column('quotation_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name='quotation_id'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('rides')
    # ### end Alembic commands ###
