"""Added quotation_id foreign key to Ride model

Revision ID: adde6b258312
Revises: 588dac6d9227
Create Date: 2023-07-31 12:16:59.833299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adde6b258312'
down_revision = '588dac6d9227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quotation_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('quotation_id', 'quotations', ['quotation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('quotation_id')

    # ### end Alembic commands ###
