"""made changes in  quotation and ride model

Revision ID: d785a270f7e4
Revises: 112cbe7c00cf
Create Date: 2023-07-30 15:39:16.411794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd785a270f7e4'
down_revision = '112cbe7c00cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quotation_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_ride_trip_id', 'quotations', ['quotation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('quotation_id')

    # ### end Alembic commands ###
